### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mjmaher987** [FrancescoPase/Federated-KLMS#1]
(pid=1802) 2024-10-24 12:50:50.409396: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=1802) 2024-10-24 12:50:50.444565: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=1802) 2024-10-24 12:50:50.457172: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=1802) 2024-10-24 12:50:52.281603: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Round 0 - Loss: 2.3068606853485107  /  Accuracy: 9.8
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flwr/simulation/app.py", line 339, in start_simulation
    hist = run_fl(
  File "/usr/local/lib/python3.10/dist-packages/flwr/server/server.py", line 492, in run_fl
    hist, elapsed_time = server.fit(
  File "/usr/local/lib/python3.10/dist-packages/flwr/server/server.py", line 115, in fit
    res_fit = self.fit_round(
  File "/usr/local/lib/python3.10/dist-packages/flwr/server/server.py", line 251, in fit_round
    ] = self.strategy.aggregate_fit(server_round, results, failures)
  File "/content/Federated-KLMS/flower_fl/strategies/lsd_strategy.py", line 147, in aggregate_fit
    updated_params.append(param.cpu().numpy() - (self.params.get('lsd').get('server_lr') * delta_layers[k]))
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/Federated-KLMS/main.py", line 99, in <module>
    flwr.simulation.start_simulation(
  File "/usr/local/lib/python3.10/dist-packages/flwr/simulation/app.py", line 375, in start_simulation
    raise RuntimeError("Simulation crashed.") from ex
RuntimeError: Simulation crashed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flwr/simulation/app.py", line 339, in start_simulation
    hist = run_fl(
  File "/usr/local/lib/python3.10/dist-packages/flwr/server/server.py", line 492, in run_fl
    hist, elapsed_time = server.fit(
  File "/usr/local/lib/python3.10/dist-packages/flwr/server/server.py", line 115, in fit
    res_fit = self.fit_round(
  File "/usr/local/lib/python3.10/dist-packages/flwr/server/server.py", line 251, in fit_round
    ] = self.strategy.aggregate_fit(server_round, results, failures)
  File "/content/Federated-KLMS/flower_fl/strategies/lsd_strategy.py", line 147, in aggregate_fit
    updated_params.append(param.cpu().numpy() - (self.params.get('lsd').get('server_lr') * delta_layers[k]))
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/Federated-KLMS/main.py", line 99, in <module>
    flwr.simulation.start_simulation(
  File "/usr/local/lib/python3.10/dist-packages/flwr/simulation/app.py", line 375, in start_simulation
    raise RuntimeError("Simulation crashed.") from ex
RuntimeError: Simulation crashed.

**Comment by mjmaher987** [comment]
Link to colab:
https://colab.research.google.com/drive/1UkmKRqqe1cxLLNQC0UYbEO0cL3T4GkLU?usp=sharing

**Comment by YYYYzhuo** [comment]
> colab 链接： [https://colab.research.google.com/drive/1UkmKRqqe1cxLLNQC0UYbEO0cL3T4GkLU?usp =sharing](https://colab.research.google.com/drive/1UkmKRqqe1cxLLNQC0UYbEO0cL3T4GkLU?usp=sharing)
Is it solved?
